name: Github Pages Deployment
on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              uses: npm install

            - name: Deploy gh-pages
              uses: npm run deploy
